// OpenCode Zen models (pay-as-you-go gateway)
// https://opencode.ai/docs/zen/
pub const DEFAULT_MODEL: &str = "gpt-5.4";
pub const SUPPORTED_MODELS: &[&str] = &[
    "gpt-5.4",
    "gpt-5.4-pro",
    "gpt-5.4-mini",
    "gpt-5.4-nano",
    "gpt-5.3-codex",
    "gpt-5.3-codex-spark",
    "gpt-5.2",
    "gpt-5.2-codex",
    "gpt-5.1",
    "gpt-5.1-codex",
    "gpt-5.1-codex-max",
    "gpt-5.1-codex-mini",
    "gpt-5",
    "gpt-5-codex",
    "gpt-5-nano",
    "claude-opus-4-7",
    "claude-opus-4-6",
    "claude-opus-4-5",
    "claude-opus-4-1",
    "claude-sonnet-4-6",
    "claude-sonnet-4-5",
    "claude-sonnet-4",
    "claude-haiku-4-5",
    "claude-3-5-haiku",
    "gemini-3.1-pro",
    "gemini-3-flash",
    "qwen3.6-plus",
    "qwen3.5-plus",
    "minimax-m2.5",
    "minimax-m2.5-free",
    "glm-5.1",
    "glm-5",
    "kimi-k2.5",
    "big-pickle",
    "nemotron-3-super-free",
];
pub const REASONING_MODELS: &[&str] = &[];
