use serde::{Deserialize, Serialize};

use crate::constants::commands as command_constants;

/// Command execution configuration
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct CommandsConfig {
    /// Commands that can be executed without prompting
    #[serde(default)]
    pub allow_list: Vec<String>,

    /// Additional directories that should be searched/prepended to PATH for command execution
    #[serde(default = "default_extra_path_entries")]
    pub extra_path_entries: Vec<String>,

    /// Commands that are always denied
    #[serde(default)]
    pub deny_list: Vec<String>,

    /// Glob patterns allowed for shell commands (applies to Bash)
    #[serde(default)]
    pub allow_glob: Vec<String>,

    /// Glob patterns denied for shell commands
    #[serde(default)]
    pub deny_glob: Vec<String>,

    /// Regex allow patterns for shell commands
    #[serde(default)]
    pub allow_regex: Vec<String>,

    /// Regex deny patterns for shell commands
    #[serde(default)]
    pub deny_regex: Vec<String>,
}

const DEFAULT_ALLOW_LIST: &[&str] = &[
    "ls",
    "pwd",
    "cat",
    "grep",
    "find",
    "head",
    "tail",
    "wc",
    "git status",
    "git diff",
    "git log",
    "git show",
    "git branch",
    "git remote",
    "cargo check",
    "cargo build",
    "cargo build --release",
    "cargo build --profile release",
    "cargo test",
    "cargo run",
    "cargo clippy",
    "cargo fmt",
    "cargo tree",
    "cargo metadata",
    "cargo doc",
    "cargo nextest run",
    "cargo nextest",
    "rustc",
    "which",
    "echo",
    "printf",
    "date",
    "tree",
    "stat",
    "file",
    "sort",
    "uniq",
    "cut",
    "awk",
    "sed",
    "tar",
    "zip",
    "unzip",
    "gzip",
    "gunzip",
    "make",
    "cmake",
    "ninja",
    "python3",
    "python3 -m pip install",
    "python3 -m pytest",
    "python3 -m build",
    "python",
    "pip3",
    "pip",
    "virtualenv",
    "node",
    "npm",
    "npm run build",
    "npm run test",
    "npm install",
    "yarn",
    "yarn build",
    "yarn test",
    "pnpm",
    "pnpm build",
    "pnpm test",
    "bun",
    "bun install",
    "bun run",
    "bun test",
    "npx",
    "go",
    "go build",
    "go test",
    "gcc",
    "g++",
    "clang",
    "clang++",
    "javac",
    "java",
    "mvn",
    "gradle",
    "docker",
    "docker-compose",
];

impl Default for CommandsConfig {
    fn default() -> Self {
        Self {
            allow_list: DEFAULT_ALLOW_LIST.iter().map(|s| (*s).into()).collect(),
            extra_path_entries: default_extra_path_entries(),
            deny_list: vec![
                "rm -rf /".into(),
                "rm -rf ~".into(),
                "rm -rf /*".into(),
                "rm -rf /home".into(),
                "rm -rf /usr".into(),
                "rm -rf /etc".into(),
                "rm -rf /var".into(),
                "rm -rf /opt".into(),
                "rmdir /".into(),
                "rmdir /home".into(),
                "rmdir /usr".into(),
                "shutdown".into(),
                "reboot".into(),
                "halt".into(),
                "poweroff".into(),
                "init 0".into(),
                "init 6".into(),
                "systemctl poweroff".into(),
                "systemctl reboot".into(),
                "systemctl halt".into(),
                "sudo rm".into(),
                "sudo chmod 777".into(),
                "sudo chown".into(),
                "sudo passwd".into(),
                "sudo su".into(),
                "sudo -i".into(),
                "sudo bash".into(),
                "su root".into(),
                "su -".into(),
                "format".into(),
                "fdisk".into(),
                "mkfs".into(),
                "mkfs.ext4".into(),
                "mkfs.xfs".into(),
                "mkfs.vfat".into(),
                "dd if=/dev/zero".into(),
                "dd if=/dev/random".into(),
                "dd if=/dev/urandom".into(),
                "wget --no-check-certificate".into(),
                ":(){ :|:& };:".into(), // Fork bomb
                "nohup bash -i".into(),
                "exec bash -i".into(),
                "eval".into(),
                "source /etc/bashrc".into(),
                "source ~/.bashrc".into(),
                "chmod 777".into(),
                "chmod -R 777".into(),
                "chown -R".into(),
                "chgrp -R".into(),
                "rm ~/.ssh/*".into(),
                "rm -r ~/.ssh".into(),
                "cat /etc/passwd".into(),
                "cat /etc/shadow".into(),
                "cat ~/.ssh/id_*".into(),
                "tail -f /var/log".into(),
                "head -n 1 /var/log".into(),
            ],
            allow_glob: vec![
                "git *".into(),
                "cargo *".into(),
                "cargo nextest *".into(),
                "rustc *".into(),
                "python *".into(),
                "python3 *".into(),
                "pip *".into(),
                "pip3 *".into(),
                "node *".into(),
                "npm *".into(),
                "npm run *".into(),
                "yarn *".into(),
                "yarn run *".into(),
                "pnpm *".into(),
                "pnpm run *".into(),
                "bun *".into(),
                "bun run *".into(),
                "npx *".into(),
                "go *".into(),
                "gcc *".into(),
                "g++ *".into(),
                "clang *".into(),
                "clang++ *".into(),
                "javac *".into(),
                "java *".into(),
                "mvn *".into(),
                "gradle *".into(),
                "make *".into(),
                "cmake *".into(),
                "ninja *".into(),
                "docker *".into(),
                "docker-compose *".into(),
                "virtualenv *".into(),
                "tar *".into(),
                "zip *".into(),
                "unzip *".into(),
                "gzip *".into(),
                "gunzip *".into(),
            ],
            deny_glob: vec![
                "rm *".into(),
                "sudo *".into(),
                "chmod *".into(),
                "chown *".into(),
                "kill *".into(),
                "pkill *".into(),
                "systemctl *".into(),
                "service *".into(),
                "mount *".into(),
                "umount *".into(),
                "docker run *".into(),
                "kubectl *".into(),
            ],
            allow_regex: vec![
                r"^(ls|pwd|cat|grep|find|head|tail|wc|echo|printf|date|tree|stat|file|sort|uniq|cut|awk|sed|tar|zip|unzip|gzip|gunzip)\b".into(),
                r"^git (status|diff|log|show|branch|remote)\b".into(),
                r"^cargo (check|build|test|run|doc|clippy|fmt|tree|metadata|nextest)\b".into(),
                r"^rustc\b".into(),
                r"^(python|python3) (-m | )?\w*".into(),
                r"^(pip|pip3)\b".into(),
                r"^virtualenv\b".into(),
                r"^(node|npm|yarn|pnpm|bun|npx)\b".into(),
                r"^go\b".into(),
                r"^(gcc|g\+\+|clang|clang\++)\b".into(),
                r"^(javac|java)\b".into(),
                r"^(mvn|gradle)\b".into(),
                r"^(make|cmake)\b".into(),
                r"^(docker|docker-compose)\b".into(),
            ],
            deny_regex: vec![
                r"rm\s+(-rf|--force)".into(),
                r"sudo\s+.*".into(),
                r"chmod\s+.*".into(),
                r"chown\s+.*".into(),
                r"docker\s+run\s+.*--privileged".into(),
                r"kubectl\s+(delete|drain|uncordon)".into(),
            ],
        }
    }
}

fn default_extra_path_entries() -> Vec<String> {
    command_constants::DEFAULT_EXTRA_PATH_ENTRIES
        .iter()
        .map(|value| (*value).into())
        .collect()
}
