[package]
name = "xtask"
version = "0.175.2"
edition = "2024"
rust-version = "1.98.1"
publish = false

[lints]
workspace = true

[dependencies]
vtcode-core = { path = "../vtcode-core" }
clap = { workspace = true, features = ["derive"] }
clap_complete = { workspace = true }
semver = { workspace = true }
toml_edit = "0.25"
