//! opencode_go_presets — provider preset definitions for opencode_go.

use super::super::{ModelPreset, ReasoningEffortPreset};
use crate::config::constants::models::opencode_go as opencode_go_models;
use crate::config::models::Provider;
use crate::config::types::ReasoningEffortLevel;
pub(crate) fn opencode_go_presets() -> Vec<ModelPreset> {
    vec![
        ModelPreset {
            id: format!("opencode-go/{}", opencode_go_models::GROK_4_5),
            model: opencode_go_models::GROK_4_5.to_string(),
            display_name: "Grok 4.5 (OpenCode Go)".to_string(),
            description: "Grok 4.5 — xAI flagship reasoning model on the OpenCode Go plan".to_string(),
            provider: Provider::OpenCodeGo,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: vec![ReasoningEffortPreset {
                effort: ReasoningEffortLevel::Medium,
                description: "Balanced".to_string(),
            }],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(500_000),
        },
        ModelPreset {
            id: format!("opencode-go/{}", opencode_go_models::GLM_5_3),
            model: opencode_go_models::GLM_5_3.to_string(),
            display_name: "GLM-5.3 (OpenCode Go)".to_string(),
            description: "GLM-5.3 — Z.AI flagship for frontier long-horizon coding on the OpenCode Go plan".to_string(),
            provider: Provider::OpenCodeGo,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: vec![ReasoningEffortPreset {
                effort: ReasoningEffortLevel::Medium,
                description: "Balanced".to_string(),
            }],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(200_000),
        },
        ModelPreset {
            id: format!("opencode-go/{}", opencode_go_models::GLM_5_1),
            model: opencode_go_models::GLM_5_1.to_string(),
            display_name: "GLM-5.1 (OpenCode Go)".to_string(),
            description: "OpenCode Go — affordable subscription for open coding models".to_string(),
            provider: Provider::OpenCodeGo,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: vec![ReasoningEffortPreset {
                effort: ReasoningEffortLevel::Medium,
                description: "Balanced".to_string(),
            }],
            is_default: true,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(200_000),
        },
        ModelPreset {
            id: format!("opencode-go/{}", opencode_go_models::GLM_5_2),
            model: opencode_go_models::GLM_5_2.to_string(),
            display_name: "GLM-5.2 (OpenCode Go)".to_string(),
            description: "GLM-5.2 — flagship Z.AI model for long-horizon coding on the OpenCode Go plan".to_string(),
            provider: Provider::OpenCodeGo,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: vec![ReasoningEffortPreset {
                effort: ReasoningEffortLevel::Medium,
                description: "Balanced".to_string(),
            }],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(200_000),
        },
        ModelPreset {
            id: format!("opencode-go/{}", opencode_go_models::GPT_5_6_LUNA),
            model: opencode_go_models::GPT_5_6_LUNA.to_string(),
            display_name: "GPT-5.6 Luna (OpenCode Go)".to_string(),
            description: "GPT-5.6 Luna — OpenAI cost-efficient frontier model on the OpenCode Go plan".to_string(),
            provider: Provider::OpenCodeGo,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: vec![ReasoningEffortPreset {
                effort: ReasoningEffortLevel::Medium,
                description: "Balanced".to_string(),
            }],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(400_000),
        },
        ModelPreset {
            id: format!("opencode-go/{}", opencode_go_models::KIMI_K3),
            model: opencode_go_models::KIMI_K3.to_string(),
            display_name: "Kimi K3 (OpenCode Go)".to_string(),
            description: "Kimi K3 — Moonshot flagship 2.8T agentic model on the OpenCode Go plan".to_string(),
            provider: Provider::OpenCodeGo,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: vec![ReasoningEffortPreset {
                effort: ReasoningEffortLevel::Medium,
                description: "Balanced".to_string(),
            }],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(1_048_576),
        },
        ModelPreset {
            id: format!("opencode-go/{}", opencode_go_models::KIMI_K2_7_CODE),
            model: opencode_go_models::KIMI_K2_7_CODE.to_string(),
            display_name: "Kimi K2.7 Code (OpenCode Go)".to_string(),
            description: "Kimi K2.7 Code — Moonshot's most capable coding model on the OpenCode Go plan".to_string(),
            provider: Provider::OpenCodeGo,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: vec![ReasoningEffortPreset {
                effort: ReasoningEffortLevel::Medium,
                description: "Balanced".to_string(),
            }],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(256_000),
        },
        ModelPreset {
            id: format!("opencode-go/{}", opencode_go_models::KIMI_K2_6),
            model: opencode_go_models::KIMI_K2_6.to_string(),
            display_name: "Kimi K2.6 (OpenCode Go)".to_string(),
            description: "Kimi K2.6 — Moonshot 1T MoE general agentic model on the OpenCode Go plan".to_string(),
            provider: Provider::OpenCodeGo,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: vec![ReasoningEffortPreset {
                effort: ReasoningEffortLevel::Medium,
                description: "Balanced".to_string(),
            }],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(256_000),
        },
        ModelPreset {
            id: format!("opencode-go/{}", opencode_go_models::MIMO_V2_5_PRO),
            model: opencode_go_models::MIMO_V2_5_PRO.to_string(),
            display_name: "MiMo-V2.5-Pro (OpenCode Go)".to_string(),
            description: "MiMo-V2.5-Pro — Xiaomi's flagship reasoning model on the OpenCode Go plan".to_string(),
            provider: Provider::OpenCodeGo,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: vec![ReasoningEffortPreset {
                effort: ReasoningEffortLevel::Medium,
                description: "Balanced".to_string(),
            }],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(1_048_576),
        },
        ModelPreset {
            id: format!("opencode-go/{}", opencode_go_models::MIMO_V2_5),
            model: opencode_go_models::MIMO_V2_5.to_string(),
            display_name: "MiMo-V2.5 (OpenCode Go)".to_string(),
            description: "MiMo-V2.5 — Xiaomi's high-volume coding model on the OpenCode Go plan".to_string(),
            provider: Provider::OpenCodeGo,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: vec![ReasoningEffortPreset {
                effort: ReasoningEffortLevel::Medium,
                description: "Balanced".to_string(),
            }],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(1_048_576),
        },
        ModelPreset {
            id: format!("opencode-go/{}", opencode_go_models::MINIMAX_M3),
            model: opencode_go_models::MINIMAX_M3.to_string(),
            display_name: "MiniMax-M3 (OpenCode Go)".to_string(),
            description: "MiniMax-M3 — frontier multimodal coding model on the OpenCode Go plan".to_string(),
            provider: Provider::OpenCodeGo,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: vec![ReasoningEffortPreset {
                effort: ReasoningEffortLevel::Medium,
                description: "Balanced".to_string(),
            }],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(1_048_576),
        },
        ModelPreset {
            id: format!("opencode-go/{}", opencode_go_models::MINIMAX_M2_7),
            model: opencode_go_models::MINIMAX_M2_7.to_string(),
            display_name: "MiniMax-M2.7 (OpenCode Go)".to_string(),
            description: "MiniMax-M2.7 — recursive self-improvement flagship on the OpenCode Go plan".to_string(),
            provider: Provider::OpenCodeGo,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: vec![ReasoningEffortPreset {
                effort: ReasoningEffortLevel::Medium,
                description: "Balanced".to_string(),
            }],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(204_800),
        },
        ModelPreset {
            id: format!("opencode-go/{}", opencode_go_models::MUSE_SPARK_1_2_CONTRIBUTOR),
            model: opencode_go_models::MUSE_SPARK_1_2_CONTRIBUTOR.to_string(),
            display_name: "Muse Spark 1.2 Contributor (OpenCode Go)".to_string(),
            description: "Muse Spark 1.2 Contributor — Meta long-context reasoning model on the OpenCode Go plan (limited regions)".to_string(),
            provider: Provider::OpenCodeGo,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: vec![ReasoningEffortPreset {
                effort: ReasoningEffortLevel::Medium,
                description: "Balanced".to_string(),
            }],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(1_048_576),
        },
        ModelPreset {
            id: format!("opencode-go/{}", opencode_go_models::QWEN_3_8_MAX),
            model: opencode_go_models::QWEN_3_8_MAX.to_string(),
            display_name: "Qwen3.8 Max (OpenCode Go)".to_string(),
            description: "Qwen3.8 Max — highest capability Qwen tier on the OpenCode Go plan".to_string(),
            provider: Provider::OpenCodeGo,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: vec![ReasoningEffortPreset {
                effort: ReasoningEffortLevel::Medium,
                description: "Balanced".to_string(),
            }],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(256_000),
        },
        ModelPreset {
            id: format!("opencode-go/{}", opencode_go_models::QWEN_3_7_MAX),
            model: opencode_go_models::QWEN_3_7_MAX.to_string(),
            display_name: "Qwen3.7 Max (OpenCode Go)".to_string(),
            description: "Qwen3.7 Max — highest capability Qwen tier on the OpenCode Go plan".to_string(),
            provider: Provider::OpenCodeGo,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: vec![ReasoningEffortPreset {
                effort: ReasoningEffortLevel::Medium,
                description: "Balanced".to_string(),
            }],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(256_000),
        },
        ModelPreset {
            id: format!("opencode-go/{}", opencode_go_models::QWEN_3_7_PLUS),
            model: opencode_go_models::QWEN_3_7_PLUS.to_string(),
            display_name: "Qwen3.7 Plus (OpenCode Go)".to_string(),
            description: "Qwen3.7 Plus — balanced Qwen coding tier on the OpenCode Go plan".to_string(),
            provider: Provider::OpenCodeGo,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: vec![ReasoningEffortPreset {
                effort: ReasoningEffortLevel::Medium,
                description: "Balanced".to_string(),
            }],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(256_000),
        },
        ModelPreset {
            id: format!("opencode-go/{}", opencode_go_models::QWEN_3_6_PLUS),
            model: opencode_go_models::QWEN_3_6_PLUS.to_string(),
            display_name: "Qwen3.6 Plus (OpenCode Go)".to_string(),
            description: "Qwen3.6 Plus — cost-effective Qwen coding tier on the OpenCode Go plan".to_string(),
            provider: Provider::OpenCodeGo,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: vec![ReasoningEffortPreset {
                effort: ReasoningEffortLevel::Medium,
                description: "Balanced".to_string(),
            }],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(256_000),
        },
        ModelPreset {
            id: format!("opencode-go/{}", opencode_go_models::DEEPSEEK_V4_PRO),
            model: opencode_go_models::DEEPSEEK_V4_PRO.to_string(),
            display_name: "DeepSeek V4 Pro (OpenCode Go)".to_string(),
            description: "DeepSeek V4 Pro — high-quality reasoning model on the OpenCode Go plan".to_string(),
            provider: Provider::OpenCodeGo,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: vec![ReasoningEffortPreset {
                effort: ReasoningEffortLevel::Medium,
                description: "Balanced".to_string(),
            }],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(128_000),
        },
        ModelPreset {
            id: format!("opencode-go/{}", opencode_go_models::DEEPSEEK_V4_FLASH),
            model: opencode_go_models::DEEPSEEK_V4_FLASH.to_string(),
            display_name: "DeepSeek V4 Flash (OpenCode Go)".to_string(),
            description: "DeepSeek V4 Flash — fast, low-cost coding model on the OpenCode Go plan".to_string(),
            provider: Provider::OpenCodeGo,
            default_reasoning_effort: ReasoningEffortLevel::Low,
            supported_reasoning_efforts: vec![ReasoningEffortPreset {
                effort: ReasoningEffortLevel::Low,
                description: "Fast".to_string(),
            }],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(128_000),
        },
        ModelPreset {
            id: format!("opencode-go/{}", opencode_go_models::HY3),
            model: opencode_go_models::HY3.to_string(),
            display_name: "Hy3 (OpenCode Go)".to_string(),
            description: "Hy3 — high-volume coding model on the OpenCode Go plan".to_string(),
            provider: Provider::OpenCodeGo,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: vec![ReasoningEffortPreset {
                effort: ReasoningEffortLevel::Medium,
                description: "Balanced".to_string(),
            }],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(1_048_576),
        },
    ]
}
