pub mod anthropic;
pub mod copilot;
pub mod deepseek;
pub mod evolink;
pub mod google;
pub mod huggingface;
pub mod llamacpp;
pub mod lmstudio;
pub mod merge_gateway;
pub mod meta;
pub mod mimo;
pub mod minimax;
pub mod mistral;
pub mod moonshot;
pub mod nvidia;
pub mod ollama;
pub mod openai;
pub mod opencode_go;
pub mod opencode_zen;
pub mod openresponses;
pub mod openrouter;
pub mod poolside;
pub mod qwen;
pub mod stepfun;
pub mod vercel;
pub mod xai;
pub mod zai;

// Backwards compatibility - keep old constants working
pub const GEMINI_3_7_FLASH: &str = google::GEMINI_3_7_FLASH;
pub const GEMINI_3_6_FLASH: &str = google::GEMINI_3_6_FLASH;
pub const GEMINI_3_8_FLASH: &str = google::GEMINI_3_8_FLASH;
pub const GEMINI_3_FLASH_PREVIEW: &str = google::GEMINI_3_FLASH_PREVIEW;
pub(crate) const GPT: &str = openai::GPT;
pub const GPT_5: &str = openai::GPT_5;
pub const GPT_5_6: &str = openai::GPT_5_6;
pub const GPT_5_6_SOL: &str = openai::GPT_5_6_SOL;
pub const GPT_5_CODEX: &str = openai::GPT_5_CODEX;
pub const GPT_5_1_CODEX: &str = openai::GPT_5_1_CODEX;
pub const GPT_5_1_CODEX_MAX: &str = openai::GPT_5_1_CODEX_MAX;
pub const GPT_5_MINI: &str = openai::GPT_5_MINI;
pub const GPT_5_NANO: &str = openai::GPT_5_NANO;
pub const O3: &str = openai::O3;
pub const O4_MINI: &str = openai::O4_MINI;
pub const GPT_OSS_20B: &str = openai::GPT_OSS_20B;
pub const GPT_OSS_120B: &str = openai::GPT_OSS_120B;
pub const CLAUDE_SONNET_5: &str = anthropic::CLAUDE_SONNET_5;
pub const CLAUDE_SONNET_5_5: &str = anthropic::CLAUDE_SONNET_5_5;
pub const CLAUDE_HAIKU_5_5: &str = anthropic::CLAUDE_HAIKU_5_5;
pub const CLAUDE_OPUS_5: &str = anthropic::CLAUDE_OPUS_5;
pub const CLAUDE_OPUS_5_5: &str = anthropic::CLAUDE_OPUS_5_5;
pub(crate) const CLAUDE_FABLE_5: &str = anthropic::CLAUDE_FABLE_5;
pub(crate) const CLAUDE_FABLE_5_1: &str = anthropic::CLAUDE_FABLE_5_1;
pub const COPILOT: &str = copilot::DEFAULT_MODEL;
pub const MINIMAX_M3: &str = minimax::MINIMAX_M3;
